function dx_nonline = state_eq_nonline(g,Mp,Jp,l,u_1,u_3,Mw,Jw,a,u_2,u_4,in12,tau,ex_tau)
%STATE_EQ_NONLINE
%    DX_NONLINE = STATE_EQ_NONLINE(G,Mp,Jp,L,U_1,U_3,Mw,Jw,A,U_2,U_4,IN12,TAU,EX_TAU)

%    This function was generated by the Symbolic Math Toolbox version 24.1.
%    2024/08/15 03:02:48

x_temp1 = in12(1,:);
x_temp2 = in12(2,:);
x_temp4 = in12(4,:);
t2 = cos(x_temp1);
t3 = sin(x_temp1);
t4 = Jw.*ex_tau;
t5 = Jw.*tau;
t6 = Mp.^2;
t7 = a.^2;
t8 = l.^2;
t9 = x_temp1.*2.0;
t10 = x_temp2.^2;
t12 = Jw.*u_1.*x_temp2;
t13 = Jw.*u_2.*x_temp4;
t14 = Jw.*u_4.*x_temp2;
t15 = Jw.*u_4.*x_temp4;
t17 = Jw.*u_3.*x_temp4.*2.0;
t11 = sin(t9);
t16 = -t5;
t18 = -t12;
t19 = Mp.*ex_tau.*t7;
t20 = Mw.*ex_tau.*t7;
t21 = Mp.*t7.*tau;
t22 = Mw.*t7.*tau;
t23 = Mp.*t7.*u_1.*x_temp2;
t24 = Mp.*t7.*u_2.*x_temp4;
t25 = Mp.*t7.*u_4.*x_temp2;
t26 = Mp.*t7.*u_4.*x_temp4;
t27 = Mw.*t7.*u_1.*x_temp2;
t28 = Mw.*t7.*u_2.*x_temp4;
t29 = Mw.*t7.*u_4.*x_temp2;
t30 = Mw.*t7.*u_4.*x_temp4;
t31 = Jw.*Mp.*g.*l.*t3;
t32 = Mp.*t7.*u_3.*x_temp4.*2.0;
t33 = Mw.*t7.*u_3.*x_temp4.*2.0;
t38 = Mp.*Mw.*g.*l.*t3.*t7;
t39 = t6.*t7.*t8;
t40 = g.*l.*t3.*t6.*t7;
t34 = -t21;
t35 = -t22;
t36 = -t23;
t37 = -t27;
t41 = (t10.*t11.*t39)./2.0;
t42 = -t41;
mt1 = [x_temp2;(t4+t13+t14+t15+t16+t17+t18+t19+t20+t24+t25+t26+t28+t29+t30+t31+t32+t33+t34+t35+t36+t37+t38+t40+t42-Mp.*a.*l.*t2.*tau+Mp.*a.*l.*t2.*u_2.*x_temp4+Mp.*a.*l.*t2.*u_4.*x_temp2+Mp.*a.*l.*t2.*u_3.*x_temp4+Mp.*a.*l.*t2.*u_4.*x_temp4)./(t39-t2.^2.*t39+Jp.*Jw+Jp.*Mp.*t7+Jp.*Mw.*t7+Jw.*Mp.*t8+Mp.*Mw.*t7.*t8);x_temp4];
mt2 = [((t4+t13+t14+t15+t16+t17+t18+t19+t20+t24+t25+t26+t28+t29+t30+t31+t32+t33+t34+t35+t36+t37+t38+t40+t42-Jp.*tau-Mp.*t8.*tau+Jp.*u_2.*x_temp4+Jp.*u_4.*x_temp2+Jp.*u_3.*x_temp4+Jp.*u_4.*x_temp4+Mp.*t8.*u_2.*x_temp4+Mp.*t8.*u_4.*x_temp2+Mp.*t8.*u_3.*x_temp4+Mp.*t8.*u_4.*x_temp4+Mp.*a.*ex_tau.*l.*t2-Mp.*a.*l.*t2.*tau.*2.0+(a.*g.*t6.*t8.*t11)./2.0-a.*l.^3.*t3.*t6.*t10-Jp.*Mp.*a.*l.*t3.*t10-Mp.*a.*l.*t2.*u_1.*x_temp2+Mp.*a.*l.*t2.*u_2.*x_temp4.*2.0+Mp.*a.*l.*t2.*u_4.*x_temp2.*2.0+Mp.*a.*l.*t2.*u_3.*x_temp4.*3.0+Mp.*a.*l.*t2.*u_4.*x_temp4.*2.0).*-2.0)./(t39-t39.*cos(t9)+Jp.*Jw.*2.0+Jp.*Mp.*t7.*2.0+Jp.*Mw.*t7.*2.0+Jw.*Mp.*t8.*2.0+Mp.*Mw.*t7.*t8.*2.0)];
dx_nonline = [mt1;mt2];
end
